executors:
  default:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
        environment:
          RAILS_ENV: test
    working_directory: ~/repo

version: 2.1
jobs:
  build:
    executor: default
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: install dependencies
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
  
  code-check:
    executor: default
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: bundle install --jobs=4 --retry=3 --path vendor/bundle
          command: bundle install
      - run: 
          name: rubocopを実行
          command: bundle exec rubocop

workflows:
  version: 2
  workflows:
    jobs:
      - build
      - code-check:
          requires:
            - build
