version: 2

jobs:
  test:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
        environment:
          RAILS_ENV: test
      - image: circleci/mysql:5.6
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: 'ci_rails_sample_test'
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: bundle install --path vendor/bundle
      - run:
          name: 'wait for db'
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m
      - run:
          name: 'DB migration'
          command: bundle exec rake db:schema:load
      - run: 
          name: Run test
          command: bundle exec rspec


workflows:
  version: 2
  workflows:
    jobs:
      - test
