version: 2.1

executors:
  default:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
        environment:
          RAILS_ENV: test
    working_directory: ~/repo

jobs:
  checkout_code:
    executor: default
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repo

  build:
    executor: default
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: bundle install
          command: bundle install --jobs=4 --path vendor/bundle
      - save_cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
  
  code-check:
    executor: default
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run: 
          name: rubocopを実行
          command: bundle exec rubocop

workflows:
  version: 2
  workflows:
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code
      - code-check:
          requires:
            - build
