default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 
  host: 127.0.0.1

development:
  <<: *default
  database: ci_rails_sample_development

test:
  <<: *default
  database: ci_rails_sample_test

production:
  <<: *default
  database: ci_rails_sample_production
  username: ci_rails_sample
  password: <%= ENV['CI_RAILS_SAMPLE_DATABASE_PASSWORD'] %>
